image: maven:3.6.1
pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B clean
          - pipe: atlassian/ftp-deploy:0.3.2
            variables:
              USER: '$user'
              PASSWORD: '$password'
              SERVER: 'christiaandotze.dedicated.co.za'
              REMOTE_PATH: '../opt/tomcat/webapps'
  branches:
    master:
      - step:
          caches:
            - maven
          script:
            - mvn -B clean package
