pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -B clean
  branches:
   master:
   - step:
       caches:
         - maven
       script:
         - mvn -B clean package
       artifacts:
         - application/target/**
   - step:
       name: Deploy to Production
       deployment: Production
       script:
         - scp ./application/target/*.war root@$christiaandotze.dedicated.co.za:/opt/tomcat/webapps/spring-boot_rest-0.0.1-SNAPSHOT.war
